application: sydney-linux-user-group-hr
version: 2
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.png
  upload: static/images/favicon.ico

- url: /images
  static_dir: static/images

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /third_party
  static_dir: static/third_party

- url: /event/add
  login: admin
  script: editevent.py

- url: /event/[0-9]*/edit
  login: admin
  script: editevent.py

- url: /.*
  script: handler.py

skip_files:
- third_party/((?!(aeoid|gaepytz-2011c)).*)/
- third_party/gaepytz-2011c/(?!pytz)
- third_party/aeoid/demo
- third_party/mkzip
- (.*/)*.git/
