application: sydney-linux-user-group-hr
version: 9
api_version: 1
runtime: python27
threadsafe: true

builtins:
- datastore_admin: on
- appstats: on

libraries:
- name: lxml
  version: latest

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.png
  upload: static/images/favicon.ico

- url: /images
  static_dir: static/images

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /third_party
  static_dir: static/third_party

#- url: /_ah/login_required
#  script: do_openid_login.py
#
#- url: /event/add
#  login: admin
#  script: handler-admin.py
#
#- url: /event/[a-zA-Z0-9]*/(edit|publish|email|addoffer|remoffer)
#  login: admin
#  script: handler-admin.py
#
#- url: /admin/.*
#  script: $PYTHON_LIB/google/appengine/ext/admin
#  login: admin
#
#- url: /talks
#  script: handler.py
#  login: required

- url: /.*
  script: handler.py

skip_files:
- third_party/((?!(aeoid|python-gae-pytz)).*)/
- third_party/python-gae-pytz/(?!pytz)
- static/third_party/jquery.validation/(?!(.*.js|localization))
- third_party/aeoid/demo
- third_party/mkzip
- (.*/)*.git/
- .*/\..*
- .*/README
