application: sydney-linux-user-group-hr
version: 6
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.png
  upload: static/images/favicon.ico

- url: /images
  static_dir: static/images

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /third_party
  static_dir: static/third_party

- url: /event/add
  login: admin
  script: editevent.py

- url: /event/[0-9]*/edit
  login: admin
  script: editevent.py

- url: /event/[0-9]*/publish
  login: admin
  script: publishevent.py

- url: /events/admin
  login: admin
  script: adminevents.py

- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /.*
  script: handler.py

builtins:
- appstats: on

skip_files:
- third_party/((?!(aeoid|gaepytz-2011c)).*)/
- third_party/gaepytz-2011c/(?!pytz)
- third_party/aeoid/demo
- third_party/mkzip
- (.*/)*.git/
- .*/\..*
- .*/README
